keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - hidden: false
    name: NOTE
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    ignore: false
    name: DONE
settings:
  addNewCardsToTop: false
  appendNewCardsTo: log.md
  cards:
    colors:
      - color: black
        filter: placeholder
      - color: red
        filter: +urgent
  doneList: DONE
  filteredLists: []
  journalPath: /notes
  journalType: Single File
  maxLines: 10
  newCardSyntax: MARKDOWN
  taskPrefix: '###'
sync:
  useImdoneioForPriority: false
