keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - hidden: false
    ignore: false
    name: NOTE
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    ignore: false
    name: DONE
settings:
  journalType: Single File
  journalPath: /notes
  taskPrefix: '###'
  maxLines: 10
  addNewCardsToTop: false
  newCardSyntax: MARKDOWN
  appendNewCardsTo: log.md
  cards:
    colors:
      - color: black
        filter: (text = *)
      - color: black
        filter: placeholder
      - color: red
        filter: tags=urgent
  doneList: DONE
  filterHistory:
    - allTags = "coding"
    - imdone
  filteredLists: []
sync:
  useImdoneioForPriority: false
